### ISSUE TITLE
AttributeError: 'Writer' object has no attribute 'close'

### ISSUE THREAD

**Issue by junjieahaha** [mdshw5/simplesam#12]
>>> out_file = open('test.sam', 'w')
>>> out_sam = Writer(out_file, in_sam.header)
>>> out_sam.write(x)
>>> out_sam.close()

it returns 'ttributeError: 'Writer' object has no attribute 'close''
so,could it be '  >>>out_file.close()'?

**Comment by mdshw5** [comment]
Hey @junjieahaha thanks for pointing out this discrepancy. I've added a .close() method for both the Reader and Writer classes and released the change in v0.1.2.
