### ISSUE TITLE
Exception parsing SAM (but not BAM) files: ValueError: I/O operation on closed file.

### ISSUE THREAD

**Issue by bede** [mdshw5/simplesam#18]
Seems to be an issue for all the SAMs I've tested. BAMs are fine.

```
   File "<>/cli.py", line 28, in consensus
    uppercase)
  File "<>/kindel.py", line 403, in bam_to_consensus
    for ref_id, aln in parse_bam(bam_path).items():
  File "<>/kindel.py", line 115, in parse_bam
    for r in bam:
  File "<>/simplesam.py", line 171, in __next__
    return self.next()
  File "<>/simplesam.py", line 160, in next
    line = next(self.f).rstrip('\n\r')
ValueError: I/O operation on closed file.
```

Conda environment
```
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py37_1
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=1
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1c=h1de35cc_1
  - pip=19.1.1=py37_0
  - python=3.7.3=h359304d_0
  - readline=7.0=h1de35cc_5
  - setuptools=41.0.1=py37_0
  - sqlite=3.29.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - argh==0.26.2
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - biopython==1.74
    - importlib-metadata==0.19
    - more-itertools==7.2.0
    - numpy==1.17.0
    - ordereddict==1.1
    - packaging==19.1
    - pandas==0.25.0
    - pluggy==0.12.0
    - py==1.8.0
    - pyparsing==2.4.2
    - pytest==5.0.1
    - python-dateutil==2.8.0
    - pytz==2019.2
    - scipy==1.3.0
    - simplesam==0.1.3
    - six==1.12.0
    - tqdm==4.32.2
    - wcwidth==0.1.7
    - zipp==0.5.2

```

**Comment by mdshw5** [comment]
Strange. Is this operating on an open file handle to a regular file, or is this reading from stdin?

**Comment by mdshw5** [comment]
I'm not sure why you see different behavior with BAM files, but from looking at your code I can see that `bam_fh` goes out of scope as soon as you leave the context handler block:

https://github.com/bede/kindel/blob/95746e473929b10935d6ad11fba8e517b026247b/kindel/kindel.py#L104-L129

By the time you want to use `bam` on line 115, `bam_fh` has been closed by the context handler.

**Comment by bede** [comment]
I'm sorry Matt, I really should have looked into this before opening an
issue and heading home without really investigating. I carelessly changed
the scoping earlier today and lacking a test for SAM files, didn't spot the
regression.

Cheers!

**Comment by mdshw5** [comment]
No worries, and no need to apologize. Thanks for posting enough information that I could figure it out :)

**Comment by bede** [comment]
Yeah, well caught!🕵️‍♂️
https://github.com/bede/kindel/commit/0501687743ca8c0eabc91d4c1f84b2b7b9a27fbe
