### ISSUE TITLE
Sam.coords returns a range

### ISSUE THREAD

**Issue by SynedraAcus** [mdshw5/simplesam#19]
[`Sam.coords`](https://github.com/mdshw5/simplesam/blob/a63c7b2b7131b375c6865fa215d2780461db003d/simplesam.py#L502) returns a range over read coords instead of a (start, end) tuple/list that its docstring implies. Either the code or the docstring have to be fixed, because otherwise it may lead the user to make errors like (in my read mapping visualization code):

```
draw_line((hit_coords[0], y), (hit_coords[1], y), **read_svg_params)
```

**Comment by mdshw5** [comment]
Thanks for bringing this to my attention. I’ve clarified the docstring. Please let me know if there are still issues.
