### ISSUE TITLE
StopIteration causes and error in Python 3.7

### ISSUE THREAD

**Issue by tomas-fer** [mdshw5/simplesam#20]
Hello Matt,
I just found an error caused by StopIteration when running [kindel ](https://github.com/bede/kindel)(depends on simplesam) in Python 3.7. By googling I found that the problem can be easily solved as documented, e.g., [here](https://www.juandebravo.com/2018/11/09/python-37-stop-iteration/).
Could you, please, looked at this and possibly correct it?
I am not a Python developer but I was able to fix my problem by changing line 371 in [simplesam.py](https://github.com/mdshw5/simplesam/blob/master/simplesam.py).
I changed `raise StopIteration` to `return`.
However, it will be nice to change it in the source code here and [PyPI](https://pypi.org/project/simplesam/0.1.3.1).
Thank you and best wishes,
Tomas

**Comment by mdshw5** [comment]
Thanks for reporting this behavior @tomas-fer! I'll commit the fix and add Python 3.7 to the CI matrix.

**Comment by mdshw5** [comment]
This is now fixed in the latest release.

**Comment by tomas-fer** [comment]
Dear Matt,
thank you for the correction. Is it also corrected for the installation with pip?
Best wishes,
Tomas


-- 
This email has been checked for viruses by AVG.
https://www.avg.com

**Comment by mdshw5** [comment]
Yes I’ve released a new version of the package and it’s available to install using pip.
