### ISSUE TITLE
Rewrite headers when write mode is append?

### ISSUE THREAD

**Issue by xizhihui** [mdshw5/simplesam#21]
Hi, it seems that headers will be append many times if I append contents to an existing sam when these contents are not appended in just one time(open and close multiple times). Or in other words, does simplesam only support for write not append?

**Comment by mdshw5** [comment]
> Or in other words, does simplesam only support for write not append?

Thanks for asking this question. I did only consider `w` mode file objects, and did not do any check for file modes [in the source](https://simplesam.readthedocs.io/en/latest/_modules/simplesam.html#Writer). If you could describe your use case a bit maybe we can support this. One issue I can see is that appending to an existing SAM file would mean that the existing SAM headers would be immutable, since there is no way we can update just the header portion of an existing file.

**Comment by xizhihui** [comment]
Thanks for your reply! 
I just wanna split reads into single cells identified by cell barcodes in tag "CR" or "CB" (I found it is hard to do that,  maybe there are some other convenient ways.) . So it is not a common usage ~~

**Comment by mdshw5** [comment]
Ah, so you would need to either keep ~10,000 file handles open or open and append to an existing file. I think that is a reasonable use case, and I'll take a look to see how that could be implemented here.

**Comment by xizhihui** [comment]
> so you would need to either keep ~10,000 file handles open or open and append to an existing file

Yeah, it troubles me hours :sweat_smile:.
I just find some codes in [bamtools issue](https://github.com/pezmaster31/bamtools/issues/135#issuecomment-539829286), herrinca firstly sort the bam to avoid this. Hope it will help.

**Comment by mdshw5** [comment]
@xizhihui I've added some initial support for appending to existing SAM files using `simplesam.Writer`. If you pass an open file with `mode="a"` then it the `Writer` will only add a header if we determine that the SAM file is empty (new). In all other cases we just ignore the header and continue appending records to the existing file.

https://github.com/mdshw5/simplesam/blob/8e914ce48cfb3136b6c5876badc50a0e86af0a4a/simplesam.py#L223-L242

**Comment by mdshw5** [comment]
If you want to test this out, you can install from the develop branch using `pip install -e "git+https://github.com/mdshw5/simplesam.git@develop#egg=simplesam"`.

**Comment by xizhihui** [comment]
Thanks for you updating.

I've tested it. In this check [code](https://github.com/mdshw5/simplesam/blob/baf66a46dfe8c2b28f07c2fe431579428965685e/simplesam.py#L238), if mode is append and `self.file.tell() >0`, and provide no new header, it goes to the `else` branch which add a None type header. 
I modified it and worked well:
```python
        if self.file.mode == 'a' and self.file.tell() == 0:
            # We're appending to an empty file. Assume we need a header.
            self._merge_header(header)
            self._header_dict_write()
        elif self.file.mode == 'a' and self.file.tell() > 0:
            if header:
                raise NotImplementedError("Updating headers on existing SAM files is not supported.\n")
        else:
            self._merge_header(header)
            self._header_dict_write()
```

**Comment by mdshw5** [comment]
Thanks @xizhihui. I've incorporated that change and will push this as a new point release.

**Comment by mdshw5** [comment]
Closing this as the change is now in v0.1.4.0. Please let me know if there's anything else I can do to make your use case work better!
